# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-configmap.yaml

namespace: cerqlar

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: nginx

replicas:
  - name: nginx
    count: 1
