apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: cerqlar

commonLabels:
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: mongodb-config
    literals:
      - MONGO_INITDB_DATABASE=myapp

secretGenerator:
  - name: mongodb-secret
    literals:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme123

generatorOptions:
  disableNameSuffixHash: true
